{{- $ports := .Values.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.fullname" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
  annotations:
    mainPort: "{{ (index $ports 0 ).port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := $ports }}
  #{{- if and (eq ($value.port | int) 8080) (eq $value.name "admin") }}
  #{{- fail "please use another port number other than 8080 for the admin port" }}
  #{{- end -}}
    - port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}
